### ISSUE TITLE
Should I call `configure_default()` before `after_new()` ?

### ISSUE THREAD

**Issue by hkoba** [hkoba/perl-mop4import-declare#14]
T/O.

**Comment by hkoba** [comment]
Instead of changing existing api, I just added new hook.

**Comment by makamaka** [comment]
How about s/after_after_new/after_configure_default/ ?

**Comment by hkoba** [comment]
LGTM. And If we do so, for consistency, also `after_new` should be renamed to `before_configure_default`.
